# Describes library dependencies of the application. 
# origin: RM

source 'http://rubygems.org'
gem 'aegis'
gem 'rails', '=2.3.11'
gem 'mysql'
gem 'andand', '=1.3.1'
gem 'haml'
gem 'sass'
gem 'will_paginate', '=2.3.15'
gem 'clearance', '=0.8.8'
gem 'modularity', '=0.6.0'
gem 'resource_controller', '=0.6.6'
gem 'erubis', '=2.6.6'
gem 'jrails', '=0.6.0'
gem 'acts-as-taggable-on', '=2.0.6'
gem 'ruby-debug'
gem 'paperclip', '=2.3.4'
gem 'spreadsheet', '=0.6.5.2'
gem 'ancestry'
gem 'vpim'

group :development do
  gem 'query_diet', '=0.2.0'
  gem "inaction_mailer"
end

group :test do
  gem "machinist", "=1.0.6"
  gem "faker", "=0.3.1"
  gem "timecop", "=0.3.5"
  gem "shoulda", "=2.11.1"
  gem 'rspec', '=1.3.2'
  gem 'rspec-rails'
  gem 'machinist_callbacks', '=0.1.3'
  gem 'rspec_spinner', "=1.1.3"
end

group :cucumber do
  gem 'cucumber'
  gem 'cucumber-rails', :path => File.join(File.dirname(__FILE__), '/vendor/gems/cucumber-rails-0.4.1')
  gem "cucumber_factory"
  gem 'cucumber_spinner'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'rspec', '=1.3.2'
  gem 'rspec-rails'
  gem "faker", "=0.3.1"
  gem "machinist", "=1.0.6"
  gem "timecop", "=0.3.5"
  gem 'machinist_callbacks', '=0.1.3'
  gem 'launchy'
end
