# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecbac5840c986b375793248de2da7d2336c9992a474a48e5faaf233a02ce77a76e3c6834ff5cde0323d1cb4956e3d221a5ac1c00330cb27c9a76bdc0fb49c422

test:
  secret_key_base: 97a2c3f0c511365364230244ffc0200bbfe20cffb483ee811ca3bd277a15127e8a7ffe78e313b684d190df4043d6732739ffccf9898013d16f00e119c2e7866a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
